import type { Metadata } from "next";
import { DM_Sans, Space_Grotesk, DM_Mono } from "next/font/google";
import { ClerkClientProvider } from "@/components/ClerkClientProvider";
import { FlowingLines } from "@/components/FlowingLines";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const dmMono = DM_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://dropdat.app"),
  title: {
    default: "dropdat — Cross-AI memory in one click",
    template: "%s — dropdat",
  },
  description:
    "Capture any AI chat as a portable capsule. Drop it into ChatGPT, Claude, Gemini and resume the conversation instantly. Open-source MCP server for Claude Code, Cursor, Cline, Claude Desktop.",
  keywords: [
    "AI memory",
    "cross-AI memory",
    "MCP server",
    "Claude Code MCP",
    "Cursor MCP",
    "Cline MCP",
    "Claude Desktop MCP",
    "ChatGPT memory",
    "portable AI context",
    "AI capsule",
    "semantic recall",
    "vector search Claude",
    "share context between ChatGPT and Claude",
    "long-term memory coding agents",
  ],
  applicationName: "dropdat",
  authors: [{ name: "dropdat" }],
  creator: "dropdat",
  publisher: "dropdat",
  category: "developer tools",
  icons: { icon: "/seo/favicon.svg" },
  manifest: "/manifest.webmanifest",
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: "dropdat",
    url: "https://dropdat.app",
    title: "dropdat — Cross-AI memory: capture, capsule, drop anywhere",
    description:
      "One-click capture of any ChatGPT, Claude, or Gemini chat. Drop the capsule into a different AI and resume instantly. Free MCP server for Claude Code, Cursor, Cline.",
    // Image is generated by app/opengraph-image.tsx — Next.js auto-wires it.
  },
  twitter: {
    card: "summary_large_image",
    title: "dropdat — Cross-AI memory: capture, capsule, drop anywhere",
    description:
      "Capture any ChatGPT, Claude, or Gemini chat as a portable capsule. Drop it into another AI. Open-source MCP server included.",
    // Image is generated by app/twitter-image.tsx — Next.js auto-wires it.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${spaceGrotesk.variable} ${dmMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <div className="ambient-wash" aria-hidden />
        <FlowingLines />
        <ClerkClientProvider>{children}</ClerkClientProvider>
      </body>
    </html>
  );
}
